# Generated by Django 4.2.16 on 2024-11-14 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testPAS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='testPAS.survey'),
        ),
        migrations.AlterField(
            model_name='response',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testPAS.question'),
        ),
        migrations.AlterField(
            model_name='usersurveyprogress',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testPAS.survey'),
        ),
    ]
