# Generated by Django 4.2.16 on 2024-12-16 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testpas', '0002_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='code_entered',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='code_entry_date',
        ),
    ]
