# Generated by Django 4.2.16 on 2024-12-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpas', '0003_remove_participant_code_entered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='code_entered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='code_entry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
